import "./globals.css";
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import Layout from "@/components/layout";
import AppProduct from "@/providers/provider-cart";

const prompt = Prompt({
  weight: "300",
  preload: true,
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={prompt.className}
      style={{ backgroundColor: "#FFFFFF" }}
    >
      <body>
        <AppProduct>
          <Layout>{children}</Layout>
        </AppProduct>
      </body>
    </html>
  );
}
